<?php
/**
 * Created by PhpStorm.
 * User: YZ
 * Date: 12/23/13
 * Time: 7:44 PM
 */

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_flexible-content-layout-2',
    'title' => 'Flexible Content Layout',
    'fields' => array (
      array (
        'key' => 'field_52b65478154da',
        'label' => 'Row Layout',
        'name' => 'row_layout',
        'type' => 'flexible_content',
        'instructions' => 'Choose a row layout from the list below',
        'layouts' => array (
          array (
            'label' => 'Single Column',
            'name' => 'single_column',
            'display' => 'row',
            'min' => '',
            'max' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_52b884865f51d',
                'label' => 'Row width',
                'name' => 'row_width',
                'type' => 'select',
                'instructions' => 'the width of this row',
                'column_width' => '',
                'choices' => array (
                  's-12' => 'Full Page Width',
                  's-10' => 'Five Sixths of Page',
                  's-9' => 'Three Quarters of Page',
                  's-8' => 'Two Thirds of Page',
                  's-6' => 'Half Width of Page',
                  's-4' => 'One third of Page',
                  's-3' => 'One Quarter of Page',
                ),
                'default_value' => 's-12',
                'allow_null' => 0,
                'multiple' => 0,
              ),
              array (
                'key' => 'field_52b87b44f7f63',
                'label' => 'Block Type',
                'name' => 'block_type',
                'type' => 'select',
                'instructions' => 'What kind of content will be in this block',
                'column_width' => '',
                'choices' => array (
                  'Mixed' => 'Mixed',
                  'Header' => 'Header',
                  'Paragraph' => 'Paragraph',
                  'Image' => 'Image',
                  'Video' => 'Video',
                  'Product' => 'Product',
                ),
                'default_value' => 'Mixed',
                'allow_null' => 0,
                'multiple' => 0,
              ),
              array (
                'key' => 'field_52b8864e5b667',
                'label' => 'Block width',
                'name' => 'block_width',
                'type' => 'select',
                'instructions' => 'the width of this block',
                'column_width' => '',
                'choices' => array (
                  's-12' => 'Full Row Width',
                  's-8' => 'Two Thirds of Row Width',
                  's-6' => 'Half of Row Width',
                ),
                'default_value' => 's-12',
                'allow_null' => 0,
                'multiple' => 0,
              ),
              array (
                'key' => 'field_52b886e118524',
                'label' => 'Block alignment',
                'name' => 'block_alignment',
                'type' => 'select',
                'instructions' => 'the position of this block in the row',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b8864e5b667',
                      'operator' => '!=',
                      'value' => 's-12',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'choices' => array (
                  'pull-left' => 'Left',
                  'pull-right' => 'Right',
                  'center' => 'Center',
                ),
                'default_value' => 'pull-left',
                'allow_null' => 0,
                'multiple' => 0,
              ),
              array (
                'key' => 'field_52b65525154db',
                'label' => 'Image',
                'name' => 'image',
                'type' => 'image',
                'instructions' => 'Choose an image',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b87b44f7f63',
                      'operator' => '==',
                      'value' => 'Image',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => 100,
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
              ),
              array (
                'key' => 'field_52b8806430bbb',
                'label' => 'Header type',
                'name' => 'header_type',
                'type' => 'select',
                'instructions' => 'select header type',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b87b44f7f63',
                      'operator' => '==',
                      'value' => 'Header',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'choices' => array (
                  'Article header' => 'Article header',
                  'Article subheader' => 'Article subheader',
                  'Section Header' => 'Section Header',
                ),
                'default_value' => 'Article header',
                'allow_null' => 0,
                'multiple' => 0,
              ),
              array (
                'key' => 'field_52b87f5df7f64',
                'label' => 'Header',
                'name' => 'header',
                'type' => 'text',
                'instructions' => 'Enter header text',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b87b44f7f63',
                      'operator' => '==',
                      'value' => 'Header',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_52b87fa2f7f65',
                'label' => 'Paragraph',
                'name' => 'paragraph',
                'type' => 'textarea',
                'instructions' => 'Enter text',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b87b44f7f63',
                      'operator' => '==',
                      'value' => 'Paragraph',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'formatting' => 'br',
              ),
              array (
                'key' => 'field_52b88922cff4e',
                'label' => 'Video',
                'name' => 'video',
                'type' => 'text',
                'instructions' => 'paste video embed code',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b87b44f7f63',
                      'operator' => '==',
                      'value' => 'Video',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_52b88a9e3abf2',
                'label' => 'Product',
                'name' => 'product',
                'type' => 'text',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b87b44f7f63',
                      'operator' => '==',
                      'value' => 'Product',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_52b8b9ec210e4',
                'label' => 'Mixed',
                'name' => 'mixed',
                'type' => 'wysiwyg',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b87b44f7f63',
                      'operator' => '==',
                      'value' => 'Mixed',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
              ),
            ),
          ),
          array (
            'label' => 'Two Columns',
            'name' => 'two_columns',
            'display' => 'row',
            'min' => '',
            'max' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_52b88c8ce5bf4',
                'label' => 'Row width',
                'name' => 'row_width',
                'type' => 'select',
                'instructions' => 'the width of this row',
                'column_width' => '',
                'choices' => array (
                  's-12' => 'Full Page Width',
                  's-10' => 'Five Sixths of Page',
                  's-9' => 'Three Quarters of Page',
                  's-8' => 'Two Thirds of Page',
                  's-6' => 'Half Width of Page',
                  's-4' => 'One third of Page',
                  's-3' => 'One Quarter of Page',
                ),
                'default_value' => 's-12',
                'allow_null' => 0,
                'multiple' => 0,
              ),
              array (
                'key' => 'field_52b88d7dd0716',
                'label' => 'Row layout',
                'name' => 'columns_layout',
                'type' => 'select',
                'instructions' => 'the width of this row',
                'column_width' => '',
                'choices' => array (
                  'equal' => 'Equal width for both columns',
                  'wide-on-left' => 'A wider left column',
                  'wide-on-right' => 'A wider right column',
                ),
                'default_value' => 'equal',
                'allow_null' => 0,
                'multiple' => 0,
              ),
              array (
                'key' => 'field_52b88c8ce5bf3',
                'label' => 'Left column block type',
                'name' => 'left_column_block_type',
                'type' => 'select',
                'instructions' => 'What kind of content will be in this block',
                'column_width' => '',
                'choices' => array (
                  'Mixed' => 'Mixed',
                  'Header' => 'Header',
                  'Paragraph' => 'Paragraph',
                  'Image' => 'Image',
                  'Video' => 'Video',
                  'Product' => 'Product',
                ),
                'default_value' => 'Mixed',
                'allow_null' => 0,
                'multiple' => 0,
              ),
              array (
                'key' => 'field_52b893b38c460',
                'label' => 'Right column block type',
                'name' => 'right_column_block_type',
                'type' => 'select',
                'instructions' => 'What kind of content will be in this block',
                'column_width' => '',
                'choices' => array (
                  'Mixed' => 'Mixed',
                  'Header' => 'Header',
                  'Paragraph' => 'Paragraph',
                  'Image' => 'Image',
                  'Video' => 'Video',
                  'Product' => 'Product',
                ),
                'default_value' => 'Paragraph',
                'allow_null' => 0,
                'multiple' => 0,
              ),
              array (
                'key' => 'field_52b8bc538a4bb',
                'label' => 'Mixed - Left Column',
                'name' => 'left_column_mixed',
                'type' => 'wysiwyg',
                'instructions' => 'Enter text',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b88c8ce5bf3',
                      'operator' => '==',
                      'value' => 'Mixed',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
              ),
              array (
                'key' => 'field_52b8bf9956d75',
                'label' => 'Mixed - Right Column',
                'name' => 'right_column_mixed',
                'type' => 'wysiwyg',
                'instructions' => 'Enter text',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b893b38c460',
                      'operator' => '==',
                      'value' => 'Mixed',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
              ),
              array (
                'key' => 'field_52b88c8ce5bf7',
                'label' => 'Image - Left Column',
                'name' => 'left_column_image',
                'type' => 'image',
                'instructions' => 'Choose an image',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b88c8ce5bf3',
                      'operator' => '==',
                      'value' => 'Image',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => 100,
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
              ),
              array (
                'key' => 'field_52b89cbc45c07',
                'label' => 'Image - Right Column',
                'name' => 'right_column_image',
                'type' => 'image',
                'instructions' => 'Choose an image',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b893b38c460',
                      'operator' => '==',
                      'value' => 'Image',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => 100,
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
              ),
              array (
                'key' => 'field_52b88c8ce5bf8',
                'label' => 'Header type - Left Column',
                'name' => 'left_column_header_type',
                'type' => 'select',
                'instructions' => 'select header type',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b88c8ce5bf3',
                      'operator' => '==',
                      'value' => 'Header',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'choices' => array (
                  'Article header' => 'Article header',
                  'Article subheader' => 'Article subheader',
                  'Section Header' => 'Section Header',
                ),
                'default_value' => 'Article header',
                'allow_null' => 0,
                'multiple' => 0,
              ),
              array (
                'key' => 'field_52b88c8ce5bf9',
                'label' => 'Header - Left Column',
                'name' => 'left_column_header',
                'type' => 'text',
                'instructions' => 'Enter header text',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b88c8ce5bf3',
                      'operator' => '==',
                      'value' => 'Header',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_52b89cf645c08',
                'label' => 'Header type - Right Column',
                'name' => 'right_column_header_type',
                'type' => 'select',
                'instructions' => 'select header type',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b893b38c460',
                      'operator' => '==',
                      'value' => 'Header',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'choices' => array (
                  'Article header' => 'Article header',
                  'Article subheader' => 'Article subheader',
                  'Section Header' => 'Section Header',
                ),
                'default_value' => 'Article header',
                'allow_null' => 0,
                'multiple' => 0,
              ),
              array (
                'key' => 'field_52b89df9162a8',
                'label' => 'Header - Right Column',
                'name' => 'right_column_header',
                'type' => 'text',
                'instructions' => 'Enter header text',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b893b38c460',
                      'operator' => '==',
                      'value' => 'Header',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_52b88c8ce5bfa',
                'label' => 'Paragraph - Left Column',
                'name' => 'left_column_paragraph',
                'type' => 'textarea',
                'instructions' => 'Enter text',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b88c8ce5bf3',
                      'operator' => '==',
                      'value' => 'Paragraph',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'formatting' => 'br',
              ),
              array (
                'key' => 'field_52b89e20162a9',
                'label' => 'Paragraph - Rght Column',
                'name' => 'right_column_paragraph',
                'type' => 'textarea',
                'instructions' => 'Enter text',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b893b38c460',
                      'operator' => '==',
                      'value' => 'Paragraph',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'formatting' => 'br',
              ),
              array (
                'key' => 'field_52b88c8ce5bfb',
                'label' => 'Video - Left Column',
                'name' => 'left_column_video',
                'type' => 'text',
                'instructions' => 'paste video embed code',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b88c8ce5bf3',
                      'operator' => '==',
                      'value' => 'Video',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_52b89e7781a1a',
                'label' => 'Video - Right Column',
                'name' => 'right_column_video',
                'type' => 'text',
                'instructions' => 'paste video embed code',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b893b38c460',
                      'operator' => '==',
                      'value' => 'Video',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_52b88c8ce5bfc',
                'label' => 'Product - Left Column',
                'name' => 'left_column_product',
                'type' => 'text',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b88c8ce5bf3',
                      'operator' => '==',
                      'value' => 'Product',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_52b89e8f81a1b',
                'label' => 'Product - Right Column',
                'name' => 'right_column_product',
                'type' => 'text',
                'conditional_logic' => array (
                  'status' => 1,
                  'rules' => array (
                    array (
                      'field' => 'field_52b893b38c460',
                      'operator' => '==',
                      'value' => 'Product',
                    ),
                  ),
                  'allorany' => 'all',
                ),
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
            ),
          ),
        ),
        'button_label' => 'Add Row',
        'min' => '',
        'max' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
          'order_no' => 0,
          'group_no' => 0,
        ),
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'default',
          'order_no' => 1,
          'group_no' => 0,
        ),
      ),
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
          'order_no' => 0,
          'group_no' => 1,
        ),
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-grooming-chronicles.php',
          'order_no' => 1,
          'group_no' => 1,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
        0 => 'permalink',
        1 => 'the_content',
        2 => 'excerpt',
        3 => 'discussion',
        4 => 'comments',
        5 => 'revisions',
        6 => 'slug',
        7 => 'author',
        8 => 'format',
        9 => 'featured_image',
        10 => 'tags',
        11 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_front-page',
    'title' => 'Front Page',
    'fields' => array (
      array (
        'key' => 'field_52b67fbda398d',
        'label' => 'Header Image',
        'name' => 'header_image',
        'type' => 'image',
        'required' => 1,
        'save_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_52b68091db30b',
        'label' => 'Letter from the editor',
        'name' => 'letter_from_the_editor',
        'type' => 'wysiwyg',
        'required' => 1,
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_52b685db2a6ca',
        'label' => 'editor signature',
        'name' => 'editor_signature',
        'type' => 'image',
        'save_format' => 'url',
        'preview_size' => 'medium',
        'library' => 'all',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
          'order_no' => 0,
          'group_no' => 0,
        ),
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-front-page.php',
          'order_no' => 1,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
        0 => 'permalink',
        1 => 'the_content',
        2 => 'excerpt',
        3 => 'custom_fields',
        4 => 'discussion',
        5 => 'comments',
        6 => 'revisions',
        7 => 'slug',
        8 => 'author',
        9 => 'format',
        10 => 'featured_image',
        11 => 'categories',
        12 => 'tags',
        13 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_issue-options',
    'title' => 'Issue Options',
    'fields' => array (
      array (
        'key' => 'field_52b610fc97957',
        'label' => 'Pages',
        'name' => 'pages',
        'type' => 'relationship',
        'instructions' => 'Add pages, drag to reorder',
        'return_format' => 'object',
        'post_type' => array (
          0 => 'page',
        ),
        'taxonomy' => array (
          0 => 'all',
        ),
        'filters' => array (
          0 => 'search',
        ),
        'result_elements' => array (
          0 => 'featured_image',
          1 => 'post_type',
          2 => 'post_title',
        ),
        'max' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'issue',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_the-list-layout',
    'title' => 'The List Layout',
    'fields' => array (
      array (
        'key' => 'field_52b72ece8c569',
        'label' => 'image slot 1',
        'name' => 'image_slot_1',
        'type' => 'image',
        'save_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_52b73104ebd43',
        'label' => 'product info 1',
        'name' => 'product_info_1',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_52b7339a384ae',
        'label' => 'product link 1',
        'name' => 'product_link_1',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_52b730bed0f07',
        'label' => 'image slot 2',
        'name' => 'image_slot_2',
        'type' => 'image',
        'save_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_52b73119ebd46',
        'label' => 'product info 2',
        'name' => 'product_info_2',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_52b733a6384b3',
        'label' => 'product link 2',
        'name' => 'product_link_2',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_52b730bdd0f06',
        'label' => 'image slot 3',
        'name' => 'image_slot_3',
        'type' => 'image',
        'save_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_52b73118ebd45',
        'label' => 'product info 3',
        'name' => 'product_info_3',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_52b733a5384b1',
        'label' => 'product link 3',
        'name' => 'product_link_3',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_52b730bcd0f05',
        'label' => 'image slot 4',
        'name' => 'image_slot_4',
        'type' => 'image',
        'save_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_52b73116ebd44',
        'label' => 'product info 4',
        'name' => 'product_info_4',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_52b733a4384b0',
        'label' => 'product link 4',
        'name' => 'product_link_4',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
          'order_no' => 0,
          'group_no' => 0,
        ),
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-the-list.php',
          'order_no' => 1,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
        0 => 'permalink',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'revisions',
        6 => 'slug',
        7 => 'author',
        8 => 'tags',
        9 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
}
